version: "3"
services:
    db:
     image: mysql:latest
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     ports:
       - "3307:3306"
     environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: testdb
       MYSQL_USER: test
       MYSQL_PASSWORD: 123456 
    php:
     volumes:
       - ./web:/www/web
     depends_on:
       - db
     build: ./php-fpm
     restart: always
    nginx:
     depends_on:
       - php
     volumes:
       - ./web:/www/web
     build: ./nginx
     ports:
       - "81:80"
     restart: always
